# Build BT kernel drivers
PRODUCT_PACKAGES += $(KERNEL_MODULES_OUT)/btpower.ko
PRODUCT_PACKAGES += $(KERNEL_MODULES_OUT)/btfm_slim_codec.ko
PRODUCT_PACKAGES += $(KERNEL_MODULES_OUT)/radio-i2c-rtc6226-qca.ko
PRODUCT_PACKAGES += $(KERNEL_MODULES_OUT)/btfmcodec.ko
PRODUCT_PACKAGES += $(KERNEL_MODULES_OUT)/bt_fm_swr.ko
